variables:
  SONAR_SOURCES: src
  SONAR_PYTHON_VERSION: 3.11
  SEMVER_ENABLED: "TRUE"
  GIT_AUTHOR_NAME: "Semantic Release"
  GIT_AUTHOR_EMAIL: "semver@bia-tech.ru"
  GIT_COMMITTER_NAME: "Semantic Release"
  GIT_COMMITTER_EMAIL: "semver@bia-tech.ru"
  RELEASE_BRANCH: "$CI_DEFAULT_BRANCH"
  PRERELEASE_BRANCH: ""


include:
  - project: 'delivery/tools/cicd-steps'
    ref: 'sam-cicd'
    file:
      - cicd-python-sam-01.yaml
