variables:
  SONAR_SOURCES: .          # Сканировать все папки в проекте
  SONAR_PYTHON_VERSION: 3.11 # Использовать Python 3.11 для анализа

include:
  - project: 'delivery/tools/cicd-steps'
    ref: 'sam-cicd'
    file:
      - cicd-python-sam-01.yaml
