variables:
  SONAR_SOURCES: src
  SONAR_PYTHON_VERSION: 3.11
  SEMVER_ENABLED: "FALSE"


include:
  - project: 'delivery/tools/cicd-steps'
    ref: 'sam-cicd'
    file:
      - cicd-python-sam-01.yaml
