version: '3.8'

services:
  nopaste-app:
    build:
      context: .
      dockerfile: Dockerfile
#      target: final
    container_name: nopaste-container
#    command: "tail -f /dev/null"
    ports:
      - '8000:8000'

  nopaste-tests:
    build:
      context: .
      dockerfile: Dockerfile
#      target: test
    container_name: nopaste-tests
    command: sh -c "pip install .[dev] && pytest src/tests -v"

